### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by lorenzo-dipuccio** [amaggiulli/QLNet#277]
I get a null reference exception after computing american option price when i call option.NPV().
   at QLNet.DividendVanillaOption.Arguments.validate()
   at QLNet.Instrument.performCalculations()
   at QLNet.LazyObject.calculate()
   at QLNet.Instrument.calculate()
   at QLNet.Instrument.NPV()

Could you help me understand why?
I'm using NET Core 5.0

Here the code:

`
            Date date = new Date(opt.Date.Day,opt.Date.Month,opt.Date.Year);
            Date expiry = new Date(opt.Expiry.Day,opt.Expiry.Month,opt.Expiry.Year);
            QLNet.Settings.setEvaluationDate(date);
            var exercise = new AmericanExercise(date,expiry);
            var payoff = new PlainVanillaPayoff(opt.Type.Equals("CALL") ? Option.Type.Call : Option.Type.Put, opt.Strike);
            var option = new VanillaOption(payoff, exercise);

            // Set up the pricing engine
            BlackScholesMertonProcess process = new BlackScholesMertonProcess(
                new Handle<Quote>(new SimpleQuote(opt.Underlying)),
                new Handle<YieldTermStructure>(new FlatForward(0, new NullCalendar(),  0.015, new Actual365Fixed())), //dividend structure
                new Handle<YieldTermStructure>(new FlatForward(0, new NullCalendar(), 0.02, new Actual365Fixed())), //risk free structure
                new Handle<BlackVolTermStructure>(new BlackConstantVol(date, new NullCalendar(), 0.20, new Actual365Fixed()))
            );
            
            var engine = new FdBlackScholesVanillaEngine(process,150,150,1, new FdmSchemeDesc().CrankNicolson());
            
            option.setPricingEngine(engine);
            option.NPV();
`

**Comment by amaggiulli** [comment]
Hello @lorenzo-dipuccio, thanks for your segnalation, try to use the latest preview version : https://www.nuget.org/packages/QLNet/1.13.1-preview.4. Issue should be fixed now, I couldn't directly test with your sample because I don't how you did the setup of the "opt" variable.
