### ISSUE TITLE
Swap example unhandled exception 

### ISSUE THREAD

**Issue by grandtiger** [amaggiulli/qlnet#38]
I tried the swap example on both Win7 (VS213) and XP (VS2010), but kept getting the following exception: "Unhandled Exception: System.ApplicationException: 1 iteration: failed at 1 alive instrument, maturity 2004/09/29, reference date 2004/09/22: invalid value (-3) at index 1".

I tried debugging it but couldn't figure out what the root cause is because I am not very familiar with QuantLib and qlnet seems to be implemented quite differently from QuantLib C++ as well. I copied the Swap example code from qlnet to QuantLib-SWIG\CSharp\examples and got it to work with minimal change. Therefore the example itself is not the issue. 

I tried changing line 77 from: `double s5yQuote = 0.0443;` to `double s5yQuote = 0.0460;` and surprisingly it ran through the end without exception, but it produced two sets of identical numbers.

In addition, I found that Bootstraptraits.cs has the following code and line 110 (return -3.0) seems to be the issue, but I don't understand why it reaches that line. Could you please take a look when you get a chance? Thanks a lot in advance!

```
public double minValueAfter( int i, InterpolatedCurve c, bool validData, int f )
{
    //return Const.QL_Epsilon;

    if ( validData )
    {
        #if QL_NEGATIVE_RATES
            // no constraints.
            // We choose as min a value very unlikely to be exceeded.
            return -3.0;
        #else
            return c.data().Last() / 2.0;
        #endif
    }
    double dt = c.times()[i] - c.times()[i - 1];
    return c.data()[i - 1] * System.Math.Exp( -maxRate * dt );
}
```

Complete console output:

```
Today: Monday, 2004/09/20
Settlement date: Wednesday, 2004/09/22
====================================================================
5-year market swap-rate = 4.43%
====================================================================
        5-years swap paying 4.00%
term structure | net present value | fair spread | fair fixed rate |
--------------------------------------------------------------------
     depo-swap |          19065.88 |      -0.42% |           4.43% |
 depo-fut-swap |          19076.14 |      -0.42% |           4.43% |
 depo-FRA-swap |          19056.02 |      -0.42% |           4.43% |
--------------------------------------------------------------------
        5-years, 1-year forward swap paying 4.00%
term structure | net present value | fair spread | fair fixed rate |
--------------------------------------------------------------------
     depo-swap |          40049.46 |      -0.92% |           4.95% |
 depo-fut-swap |          40092.79 |      -0.92% |           4.95% |
 depo-FRA-swap |          37238.92 |      -0.86% |           4.88% |
====================================================================
5-year market swap-rate = 4.60%
====================================================================
        5-years swap paying 4.00%
term structure | net present value | fair spread | fair fixed rate |
--------------------------------------------------------------------

Unhandled Exception: System.ApplicationException: 1 iteration: failed at 1 alive instrument, maturity 2004/09/29, reference date 2004/09/22: invalid value (-3) at index 1
   at QLNet.Utils.QL_FAIL(String message) in C:\GitHub\qlnet\QLNet\Utils.cs:line 85
   at QLNet.IterativeBootstrap`2.calculate() in C:\GitHub\qlnet\QLNet\Termstructures\Iterativebootstrap.cs:line 223
   at QLNet.PiecewiseYieldCurve`3.performCalculations() in C:\GitHub\qlnet\QLNet\Termstructures\Yield\PiecewiseYieldCurv
e.cs:line 233
   at QLNet.LazyObject.calculate() in C:\GitHub\qlnet\QLNet\Patterns\LazyObject.cs:line 112
   at QLNet.PiecewiseYieldCurve.maxDate() in C:\GitHub\qlnet\QLNet\Termstructures\Yield\PiecewiseYieldCurve.cs:line 68
   at QLNet.TermStructure.maxTime() in C:\GitHub\qlnet\QLNet\Termstructures\TermStructure.cs:line 98
   at QLNet.TermStructure.checkRange(Double t, Boolean extrapolate) in C:\GitHub\qlnet\QLNet\Termstructures\TermStructur
e.cs:line 155
   at QLNet.YieldTermStructure.discount(Double t, Boolean extrapolate) in C:\GitHub\qlnet\QLNet\Termstructures\YieldTerm
Structure.cs:line 122
   at QLNet.YieldTermStructure.discount(Date d, Boolean extrapolate) in C:\GitHub\qlnet\QLNet\Termstructures\YieldTermSt
ructure.cs:line 114
   at QLNet.DiscountingSwapEngine.calculate() in C:\GitHub\qlnet\QLNet\Pricingengines\Swap\Discountingswapengine.cs:line
 77
   at QLNet.Instrument.performCalculations() in C:\GitHub\qlnet\QLNet\Instruments\Instrument.cs:line 78
   at QLNet.LazyObject.calculate() in C:\GitHub\qlnet\QLNet\Patterns\LazyObject.cs:line 112
   at QLNet.Instrument.calculate() in C:\GitHub\qlnet\QLNet\Instruments\Instrument.cs:line 65
   at QLNet.Instrument.NPV() in C:\GitHub\qlnet\QLNet\Instruments\Instrument.cs:line 100
   at Swap.SwapValuation.Main(String[] args) in C:\GitHub\qlnet\Examples\Swap\swapvaluation.cs:line 480
Press any key to continue . . .
```

Output for changing line 77 to set 5yr swap rate to 4.60%

```
Today: Monday, 2004/09/20
Settlement date: Wednesday, 2004/09/22
====================================================================
5-year market swap-rate = 4.60%
====================================================================
        5-years swap paying 4.00%
term structure | net present value | fair spread | fair fixed rate |
--------------------------------------------------------------------
     depo-swap |          26539.06 |      -0.58% |           4.60% |
 depo-fut-swap |          26553.34 |      -0.58% |           4.60% |
 depo-FRA-swap |          26525.34 |      -0.58% |           4.60% |
--------------------------------------------------------------------
        5-years, 1-year forward swap paying 4.00%
term structure | net present value | fair spread | fair fixed rate |
--------------------------------------------------------------------
     depo-swap |          45736.04 |      -1.06% |           5.09% |
 depo-fut-swap |          45782.40 |      -1.06% |           5.09% |
 depo-FRA-swap |          42922.60 |      -0.99% |           5.02% |
====================================================================
5-year market swap-rate = 4.60%
====================================================================
        5-years swap paying 4.00%
term structure | net present value | fair spread | fair fixed rate |
--------------------------------------------------------------------
     depo-swap |          26539.06 |      -0.58% |           4.60% |
 depo-fut-swap |          26553.34 |      -0.58% |           4.60% |
 depo-FRA-swap |          26525.34 |      -0.58% |           4.60% |
--------------------------------------------------------------------
        5-years, 1-year forward swap paying 4.00%
term structure | net present value | fair spread | fair fixed rate |
--------------------------------------------------------------------
     depo-swap |          45736.04 |      -1.06% |           5.09% |
 depo-fut-swap |          45782.40 |      -1.06% |           5.09% |
 depo-FRA-swap |          42922.60 |      -0.99% |           5.02% |

Run completed in 00:00:00.3749976
Press any key to continue ...
```

**Comment by grantathon** [comment]
Is QL_NEGATIVE_RATES not set (i.e., doesn't allow negative rates) by default in the current version of 1.4?  When I look at the data of my returned QLNet.InterpolatedCurve, which is based on certain real rates, I see values floored at zero where there should be negative values.

**Comment by igitur** [comment]
From what I gather from https://github.com/amaggiulli/qlnet/blob/Ver-1.4/QLNet/QLNet.csproj ,  believe QL_NEGATIVE_RATES was included. Can you try your code from the latest git master?

**Comment by grantathon** [comment]
I'm currently using the NuGet package of QLNet version 1.4.0.4, which appears to have been released after your "Enable QL_NEGATIVE_RATES" push.  Maybe the csproj of the NuGet package doesn't reflect this change?

**Comment by grantathon** [comment]
I'm using the most recent version of QLNet on NuGet (1.4.0.30), which appears should include the "Enable QL_NEGATIVE_RATES" push you sourced.

Strangely enough, I get a System.ApplicationException with the message "Additional information: non-positive yield" when I try

```
var qlCurve = new QLNet.InterpolatedZeroCurve<QLNet.Linear>(
                        orderedDatesAndRates.Select(x => x.Key).ToList(),
                        orderedDatesAndRates.Select(x => x.Value).ToList(),
                        dayCountConv,
                        new QLNet.Linear());
```

The first four values are negative.  Any ideas?

**Comment by igitur** [comment]
Try the git master branch.

**Comment by grantathon** [comment]
I tried the master branch as well as Ver-1.5 and both work.  Thanks!
